import { nanoid } from 'nanoid'
import { tableMergeRegionSchema } from '../../../shared/tableMerge'
import { z } from 'zod'
import { flowBlockSchema } from '../../../shared/courseProjectSchema'
import type { FlowBlock } from '../../../shared/courseProjectTypes'
import { carrierForFlowBlock, findFlowBlockRecursive, makeFlowBlockAuthoringAddress } from '../../course/flowDocumentModel'
import { insertFlowEditorBlock, updateFlowEditorBlock, deleteFlowEditorBlock, moveFlowEditorBlock, type FlowCommandResult } from '../../course/flowEditorCommands'
import { changeFlowTableStructure } from '../../course/flowTableContentOperations'
import type { AuthoringToolDefinition } from './executeAuthoringTool'
import { insertionIndex, resolveAuthoringToolScope } from './authoringToolScope'
import { nativeContentInputSchemaByType } from '../../../shared/contracts/native-v1/schema'
import { applyTextRunStyle, remapTextRuns } from '../../../shared/textRuns'

// Only the ID is generated by the tool; the public Flow parser owns all content.
const newBlock = z.record(z.string(), z.unknown()).transform((value, context): FlowBlock => {
  if ('id' in value) {
    context.addIssue({ code: 'custom', path: ['id'], message: '创建块的 ID 由工具生成' })
    return z.NEVER
  }
  const parsed = flowBlockSchema.safeParse({ ...value, id: `block-${nanoid(10)}` })
  if (!parsed.success) {
    parsed.error.issues.forEach((issue) => context.addIssue({ code: 'custom', path: issue.path, message: issue.message }))
    return z.NEVER
  }
  return parsed.data
})
const id = z.string().min(1)
const structure = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('merge'), region: tableMergeRegionSchema }).strict(),
  z.object({ kind: z.literal('split'), rowId: id, columnId: id }).strict(),
  z.object({ kind: z.literal('insert-row'), afterId: id.optional() }).strict(),
  z.object({ kind: z.literal('insert-column'), afterId: id.optional() }).strict(),
  z.object({ kind: z.literal('delete-row'), id }).strict(),
  z.object({ kind: z.literal('delete-column'), id }).strict(),
  z.object({ kind: z.literal('move-row'), id, direction: z.union([z.literal(-1), z.literal(1)]) }).strict(),
  z.object({ kind: z.literal('move-column'), id, direction: z.union([z.literal(-1), z.literal(1)]) }).strict(),
])
export const flowAuthoringToolInputSchema = z.discriminatedUnion('operation', [
  z.object({ operation: z.literal('insert'), block: newBlock }).strict(),
  z.object({ operation: z.literal('replace'), block: flowBlockSchema }).strict(),
  z.object({ operation: z.literal('edit'), text: z.string().optional(),
    image: z.object({ assetId: z.string().min(1) }).strict().optional(),
    formula: nativeContentInputSchemaByType.formula.pick({ ast: true, accessibleText: true }).extend({ accessibleText: z.string().trim().min(1).max(4_000) }).strict().optional(),
    textStyle: nativeContentInputSchemaByType.text.shape.runs.element.shape.style.optional(),
    textAlign: z.enum(['left', 'center', 'right']).optional(), lineSpacing: z.number().finite().min(0).max(200).optional() }).strict()
    .refine(value => Object.keys(value).length > 1, '正文窄编辑至少提供一个字段'),
  z.object({ operation: z.literal('delete') }).strict(),
  z.object({ operation: z.literal('move'), parentId: id.nullable(), index: z.number().int().nonnegative() }).strict(),
  z.object({ operation: z.literal('table-structure'), change: structure }).strict(),
])

export const flowAuthoringTool: AuthoringToolDefinition<z.infer<typeof flowAuthoringToolInputSchema>> = {
  name: 'flow.content',
  description: '新Flow默认fluid，沿实际容器排版；已有Flow保留其layout。普通标题、正文、图片和互动放正文block以自然占位，不用viewport绝对文字替代。insert使用create parent:flow-body，block只省略宿主生成的id。修改标题、段落或引用块优先edit的text/textStyle/textAlign/lineSpacing；公式用edit.formula的ast和accessibleText，保留formulaId；图片用edit.image.assetId，保留正文布局、说明和块身份。常规图片应用优先media.apply。未指定排版、富文本和元数据保留。replace/delete/move使用Flow block update target；replace必须保留id和类型。完整载体替换使用selection.replace。',
  inputSchema: flowAuthoringToolInputSchema,
  plan({ document, destination, value }) {
    const { target, surface } = resolveAuthoringToolScope(document, destination)
    if (surface.type !== 'flow' || target.owner !== 'surface') throw new Error('Flow 正文工具只接受 Flow surface owner')
    const options = { expectedRevision: target.documentRevision }
    let result: FlowCommandResult
    let block: FlowBlock
    let operation: 'created' | 'updated' | 'deleted'
    if (value.operation === 'insert') {
      if (destination.kind !== 'create' || destination.scope.parent.kind !== 'flow-body') throw new Error('插入正文需要 flow-body create scope')
      const parentId = destination.scope.parent.parentBlockId
      const parent = parentId === null ? null : findFlowBlockRecursive(surface.blocks, parentId)?.block
      if (parentId !== null && parent?.type !== 'section') throw new Error('Flow 父分节已失效')
      const siblings = parent?.type === 'section' ? parent.blocks : surface.blocks
      result = insertFlowEditorBlock(document, { surfaceId: surface.id, parentId,
        index: insertionIndex(siblings.map((entry) => entry.id), destination.scope.insertion), block: value.block }, options)
      block = value.block
      operation = 'created'
    } else {
      if (destination.kind !== 'update') throw new Error('更新正文需要完整 update target')
      const found = findFlowBlockRecursive(surface.blocks, destination.target.itemId)
      if (!found) throw new Error('目标正文块已失效')
      block = found.block
      const expectedAddress = makeFlowBlockAuthoringAddress({ projectId: document.id, surfaceId: surface.id, blockId: block.id, carrier: carrierForFlowBlock(block) })
      if (destination.target.authoringAddress !== expectedAddress) throw new Error('正文 authoringAddress 与目标块不匹配')
      const blockTarget = { surfaceId: surface.id, blockId: block.id, parentId: found.parentId }
      operation = value.operation === 'delete' ? 'deleted' : 'updated'
      if (value.operation === 'delete') result = deleteFlowEditorBlock(document, blockTarget, options)
      else if (value.operation === 'move') result = moveFlowEditorBlock(document, blockTarget, { parentId: value.parentId, index: value.index }, options)
      else {
        if (value.operation === 'edit') {
          const textFields = value.text !== undefined || value.textStyle !== undefined || value.textAlign !== undefined || value.lineSpacing !== undefined
          if ([textFields, value.image !== undefined, value.formula !== undefined].filter(Boolean).length !== 1) throw new Error('一次正文窄编辑只能修改一种内容类型')
          if (textFields && block.type !== 'heading' && block.type !== 'paragraph' && block.type !== 'quote') throw new Error('正文文字窄编辑只接受标题、段落或引用块')
          if (value.formula && block.type !== 'formula') throw new Error('正文公式窄编辑只接受公式块')
          if (value.image && (block.type !== 'media' || block.mediaKind !== 'image' || document.assets[value.image.assetId]?.kind !== 'image')) throw new Error('正文图片窄编辑需要图片块和有效图片资产')
        }
        const replacement = value.operation === 'edit' && (block.type === 'heading' || block.type === 'paragraph' || block.type === 'quote')
          ? (() => {
            const text = value.text ?? block.text
            const runs = remapTextRuns(block.text, text, block.runs ?? [])
            return flowBlockSchema.parse({ ...block, text,
              ...(block.runs !== undefined || value.textStyle ? { runs: value.textStyle ? applyTextRunStyle(text, runs, 0, Array.from(text).length, value.textStyle) : runs } : {}),
              ...(value.textAlign !== undefined ? { textAlign: value.textAlign } : {}), ...(value.lineSpacing !== undefined ? { lineSpacing: value.lineSpacing } : {}) })
          })()
          : value.operation === 'edit' && value.image && block.type === 'media' ? { ...block, assetId: value.image.assetId }
          : value.operation === 'edit' && value.formula && block.type === 'formula' ? { ...block, ...value.formula }
          : value.operation === 'table-structure'
          ? block.type === 'table' ? changeFlowTableStructure(block, value.change) : null
          : value.operation === 'replace' ? value.block : null
        if (!replacement || replacement.id !== block.id || replacement.type !== block.type) throw new Error('更新必须保留正文块身份与类型')
        result = updateFlowEditorBlock(document, blockTarget, replacement, options)
      }
    }
    if (!result.ok || !result.nextDocument) throw new Error(result.reason ?? 'Flow 工具提交失败')
    return {
      transaction: { projectId: document.id, baseRevision: document.revision, nextDocument: result.nextDocument, resourceChanges: {},
        selectionHint: { kind: 'authoring-tool-selection', locationId: target.locationId, stateId: null, owner: 'surface',
          itemIds: operation === 'deleted' ? [] : [block.id] } },
      affected: [{ id: block.id, operation, ownerKey: target.ownerKey,
        authoringAddress: makeFlowBlockAuthoringAddress({ projectId: document.id, surfaceId: surface.id, blockId: block.id, carrier: carrierForFlowBlock(block) }) }],
    }
  },
}
