/**
 * The one module that pulls the font binaries into a bundle.
 *
 * `virtual:bundled-fonts` is generated by `bundledFontsPlugin` in
 * `vite.renderer.config.ts`: it emits one `?url` import per `woff2` and joins
 * the resulting URLs onto the build-time descriptors. Same shape as
 * `virtual:player-bundle` / `loadPlayerBundle.ts`.
 *
 * Importing this module from the Player runtime would inline ~5.7 MB of base64
 * into `player.iife.js` (Vite's library mode has no external asset URLs, so it
 * always inlines), and that bundle is embedded into every exported lesson. The
 * Player therefore loads faces the host document declares — it never carries
 * them. `tests/unit/bundledFonts.test.ts` guards that boundary.
 */
import manifest from 'virtual:bundled-fonts'
import type { BundledFontManifest } from './bundledFontManifest'

/** Bundled font manifest with every face URL resolved by the build. */
export const BUNDLED_FONT_MANIFEST: BundledFontManifest = manifest
