import { _electron as electron, expect, test } from '@playwright/test'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, renameSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { BACKGROUND_E2E_ENV } from '../../src/main/windowVisibility'

const root = resolve(__dirname, '../..')

test('M10 Windows tree actions, shortcut focus and watcher identity', async ({}, info) => {
  test.skip(process.platform !== 'win32', 'Windows Explorer actions require the Windows desktop carrier.')
  test.setTimeout(120_000)
  const base = join(root, 'output/g20/m10'); mkdirSync(base, { recursive: true })
  const directory = mkdtempSync(join(base, 'run-'))
  const workspace = join(directory, 'workspace'); mkdirSync(workspace)
  writeFileSync(join(workspace, 'copy.md'), 'copy me')
  writeFileSync(join(workspace, 'move.md'), 'move me')
  writeFileSync(join(workspace, 'drag.md'), 'drag me')
  const app = await electron.launch({ cwd: root, args: ['.', `--user-data-dir=${join(directory, 'profile')}`],
    env: { ...process.env, VITE_DEV_SERVER_URL: '', [BACKGROUND_E2E_ENV]: '1' } })
  try {
    const page = await app.firstWindow()
    const errors: string[] = []
    page.on('pageerror', error => errors.push(error.message))
    await app.evaluate(({ dialog }, selected) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [selected] }) }, workspace)
    await page.getByLabel('切换工作空间').click()
    await page.getByRole('button', { name: '选择其他工作空间文件夹…', exact: true }).click()
    const files = page.locator('.workspace-files-tree')
    const tree = files.getByRole('tree', { name: '工作空间文件' })
    await expect(tree.getByRole('button', { name: 'copy.md', exact: true })).toBeVisible()
    await expect(page.getByRole('region', { name: '资源管理器' })).toBeVisible()
    const toolbar = files.getByRole('toolbar', { name: '文件管理' })
    await expect(toolbar.locator(':scope > button')).toHaveCount(1)
    await expect(toolbar.locator(':scope > details')).toHaveCount(1)

    await tree.getByRole('button', { name: '工作空间根目录' }).click()
    await files.locator('summary[aria-label="新建文件或文件夹"]').click()
    await files.getByRole('button', { name: '新建文件夹' }).click()
    await files.getByLabel('文件名称').fill('notes')
    await files.getByRole('button', { name: '确认' }).click()
    await expect(tree.getByRole('button', { name: 'notes', exact: true })).toBeVisible()
    expect(existsSync(join(workspace, 'notes'))).toBe(true)
    const folder = tree.getByRole('button', { name: 'notes', exact: true })
    await folder.click()
    await files.locator('summary[aria-label="新建文件或文件夹"]').click()
    await files.getByRole('button', { name: '新建文本文件' }).click()
    await files.getByLabel('文件名称').fill('created.txt')
    await files.getByRole('button', { name: '确认' }).click()
    await expect.poll(() => existsSync(join(workspace, 'notes', 'created.txt'))).toBe(true)
    await tree.getByRole('button', { name: 'created.txt', exact: true }).click({ button: 'right' })
    await expect(files.getByRole('menu', { name: '文件菜单' })).toBeVisible()
    await tree.getByRole('button', { name: 'created.txt', exact: true }).press('Escape')
    await expect(files.getByRole('menu', { name: '文件菜单' })).toHaveCount(0)

    const copy = tree.getByRole('button', { name: 'copy.md', exact: true })
    await copy.click(); await copy.press('Control+C')
    await folder.click(); await folder.press('Control+V')
    await expect.poll(() => existsSync(join(workspace, 'notes', 'copy.md'))).toBe(true)
    expect(readFileSync(join(workspace, 'copy.md'), 'utf8')).toBe('copy me')

    const move = tree.getByRole('button', { name: 'move.md', exact: true })
    await move.click(); await move.press('Control+X')
    await folder.click(); await folder.press('Control+V')
    await expect.poll(() => existsSync(join(workspace, 'notes', 'move.md'))).toBe(true)
    expect(existsSync(join(workspace, 'move.md'))).toBe(false)

    const drag = tree.getByRole('button', { name: 'drag.md', exact: true })
    await drag.dragTo(folder)
    await expect.poll(() => existsSync(join(workspace, 'notes', 'drag.md'))).toBe(true)
    expect(existsSync(join(workspace, 'drag.md'))).toBe(false)

    const moved = tree.getByRole('button', { name: 'move.md', exact: true })
    await moved.click(); await moved.press('F2')
    const rename = files.getByLabel('文件名称')
    await rename.press('Control+A'); await rename.press('Delete')
    await expect(rename).toHaveValue('')
    expect(existsSync(join(workspace, 'notes', 'move.md'))).toBe(true)
    await rename.fill('renamed.md'); await rename.press('Enter')
    await expect.poll(() => existsSync(join(workspace, 'notes', 'renamed.md'))).toBe(true)

    const chat = page.getByLabel('给创作助手发消息')
    await chat.fill('聊天文字')
    await chat.press('Control+A'); await chat.press('Delete')
    expect(existsSync(join(workspace, 'notes', 'renamed.md'))).toBe(true)
    await expect(files.getByRole('dialog')).toHaveCount(0)

    await app.evaluate(({ dialog }) => { dialog.showMessageBox = async () => ({ response: 0, checkboxChecked: false }) })
    const renamed = tree.getByRole('button', { name: 'renamed.md', exact: true })
    await renamed.click(); await renamed.press('Delete')
    await expect.poll(() => existsSync(join(workspace, 'notes', 'renamed.md'))).toBe(false)

    const preserved = tree.getByRole('button', { name: 'copy.md', exact: true }).last()
    await preserved.click()
    const selectedId = await preserved.getAttribute('data-entry-id')
    const folderId = await folder.getAttribute('data-entry-id')
    renameSync(join(workspace, 'notes'), join(workspace, 'renamed-notes'))
    const renamedFolder = tree.getByRole('button', { name: 'renamed-notes', exact: true })
    await expect(renamedFolder).toBeVisible()
    await expect(renamedFolder).toHaveAttribute('data-entry-id', folderId!)
    await expect(renamedFolder.locator('xpath=ancestor::li[1]')).toHaveAttribute('data-open', 'true')
    await expect(tree.getByRole('button', { name: 'copy.md', exact: true }).last()).toHaveAttribute('data-entry-id', selectedId!)
    await expect(tree.getByRole('button', { name: 'copy.md', exact: true }).last()).toHaveAttribute('aria-pressed', 'true')
    expect(errors).toEqual([])
    const screenshot = join(directory, 'tree-actions.png')
    await page.screenshot({ path: screenshot })
    await info.attach('tree-actions', { path: screenshot, contentType: 'image/png' })
  } finally {
    await app.evaluate(({ app, BrowserWindow }) => { BrowserWindow.getAllWindows().forEach(window => window.destroy()); app.exit(0) }).catch(() => {})
    await app.close().catch(() => {})
  }
})
