/** The complete editable default UI is embedded in the course package. */
export const DEFAULT_TEACHER_CONTROLLER_SOURCE = String.raw`
window.CoursewareComponent.define({
  id: "com.ittoedu.teacher-controller", runtimeApiVersion: 4,
  create(ctx) {
    const root = ctx.dom.root, doc = root.ownerDocument, host = ctx.teacherController;
    let props=ctx.props, disposed=false, open=null;
    const loadedImages=new Set();
    const css=doc.createElement('style');
    css.textContent=
      '.controller{position:absolute;bottom:0;display:flex;align-items:center;gap:12px;width:100%;min-height:64px;padding:8px;border:1px solid color-mix(in srgb,var(--ink) 15%,transparent);border-radius:var(--radius);background:var(--paper);color:var(--ink);box-shadow:0 12px 36px #0f172a26,0 2px 6px #0f172a14;font:500 13px/1.4 system-ui,"Microsoft YaHei",sans-serif;pointer-events:auto;cursor:grab;touch-action:none;isolation:isolate}'+
      '.controller *{box-sizing:border-box}.controller button{display:inline-flex;align-items:center;justify-content:center;gap:7px;min-width:40px;height:40px;flex-shrink:0;padding:0 11px;border:1px solid transparent;border-radius:11px;background:transparent;color:inherit;font:inherit;cursor:pointer;pointer-events:auto;white-space:nowrap;transition:background .15s,box-shadow .15s}'+
      '.controller button:hover:not(:disabled){background:color-mix(in srgb,var(--ink) 10%,transparent)}.controller button:active:not(:disabled){background:color-mix(in srgb,var(--ink) 16%,transparent)}'+
      '.controller button:focus-visible{outline:2px solid var(--accent);outline-offset:3px}.controller button:disabled{opacity:.32;cursor:default}.controller svg{width:19px;height:19px;flex-shrink:0;fill:none;stroke:currentColor;stroke-width:1.7;stroke-linecap:round;stroke-linejoin:round}'+
      '.controller .launcher{width:46px;height:46px;padding:0;border-radius:50%;background:color-mix(in srgb,var(--accent) 16%,transparent);color:var(--accent)}'+
      '.identity{display:flex;flex-direction:column;justify-content:center;gap:3px;min-width:90px;max-width:180px;cursor:grab;touch-action:none;pointer-events:auto}.identity strong{font-size:13px;font-weight:650;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.progress{font-size:11px;opacity:.65;font-variant-numeric:tabular-nums}.track{height:2px;border-radius:2px;background:color-mix(in srgb,var(--ink) 12%,transparent);overflow:hidden}.track i{display:block;height:100%;background:var(--accent);border-radius:2px}'+
      '.group{display:flex;align-items:center;gap:4px}.steps{margin-left:4px;padding-left:12px;border-left:1px solid color-mix(in srgb,var(--ink) 14%,transparent)}.tools{margin-left:auto;flex-wrap:wrap;justify-content:flex-end}'+
      '.controller .primary{background:var(--accent);color:var(--accent-ink);padding:0 18px;font-weight:650}.controller .primary:hover:not(:disabled){background:var(--accent);box-shadow:inset 0 0 0 100px #ffffff1f}.controller button[aria-expanded=true]{background:color-mix(in srgb,var(--accent) 18%,transparent);color:var(--accent)}'+
      '.controller .launcher{order:4;margin-left:auto}.controller.collapsed{width:52px;height:52px;min-height:52px;padding:2px;gap:0;border-radius:50%}.collapsed .launcher{width:46px;height:46px}.controller.compact .identity{display:none}'+
      '.popover{position:absolute;bottom:calc(100% + 12px);right:0;width:320px;max-width:calc(100vw - 24px);padding:12px;border-radius:16px;border:1px solid color-mix(in srgb,var(--ink) 16%,transparent);background:var(--paper-solid);color:var(--ink);box-shadow:0 16px 48px #0f172a33;pointer-events:auto}.popover header{display:flex;align-items:center;justify-content:space-between;gap:8px;padding:0 0 8px 8px;font-weight:650}.popover header small{font-size:11px;opacity:.55;font-weight:400;margin-left:8px}.popover header button{width:30px;min-width:30px;height:30px;padding:0}.scene-list{display:flex;flex-direction:column;gap:3px;max-height:300px;overflow-y:auto;overscroll-behavior:contain;scrollbar-width:thin}.controller .scene-row{width:100%;justify-content:flex-start;min-height:42px;height:auto;padding:9px 10px;white-space:normal;text-align:left}.scene-row span{overflow:hidden;text-overflow:ellipsis}.scene-row em{min-width:25px;font-style:normal;font-size:11px;opacity:.55;font-variant-numeric:tabular-nums}.controller .scene-row[aria-current=page]{background:color-mix(in srgb,var(--accent) 17%,transparent);color:var(--accent)}.zoom-row{display:flex;align-items:center;justify-content:space-between;gap:8px}.zoom-value{font-size:18px;font-weight:600;font-variant-numeric:tabular-nums}.controller .reset{width:100%;margin-top:8px;background:color-mix(in srgb,var(--ink) 6%,transparent)}'+
      '@container controller (max-width:760px){.controller{gap:6px}.identity{max-width:110px}.steps{padding-left:6px;margin-left:0}.tools{gap:0}.controller button{padding:0 8px;min-width:36px}.controller .primary{padding:0 12px}}'+
      '@container controller (max-width:560px){.controller:not(.collapsed){flex-wrap:wrap}.identity{max-width:none;flex:1}.steps{border-left:0;margin-left:auto}.tools{width:calc(100% - 58px);margin-left:0;justify-content:center;border-top:1px solid color-mix(in srgb,var(--ink) 12%,transparent);padding-top:5px}}'+
      '@media(prefers-reduced-motion:reduce){.controller button{transition:none}}';
    const panel=doc.createElement('nav');panel.setAttribute('aria-label','教师控制台');
    root.append(css,panel);Object.assign(root.style,{pointerEvents:'none',overflow:'visible',containerType:'inline-size',containerName:'controller'});
    const paths={panel:'M4 5h16v14H4z M9 5v14 M12 9h5 M12 13h5',left:'m14 6-6 6 6 6',right:'m9 6 6 6-6 6',previous:'m12 6-6 6 6 6 M18 6l-6 6 6 6',next:'m6 6 6 6-6 6 M12 6l6 6-6 6',list:'M9 6h11 M9 12h11 M9 18h11 M4 6h.01 M4 12h.01 M4 18h.01',replay:'M4 10a8 8 0 1 1 1 8 M4 4v6h6',sound:'m11 5-5 4H3v6h3l5 4z M15 8a6 6 0 0 1 0 8 M18 5a10 10 0 0 1 0 14',muted:'m11 5-5 4H3v6h3l5 4z M16 9l5 6 M21 9l-5 6',full:'M8 3H3v5 M16 3h5v5 M3 16v5h5 M21 16v5h-5',zoom:'M16 16l5 5 M10 4a6 6 0 1 0 0 12 6 6 0 0 0 0-12',minus:'M5 12h14',plus:'M5 12h14 M12 5v14',close:'m6 6 12 12 M18 6 6 18'};
    function icon(name){const el=doc.createElementNS('http://www.w3.org/2000/svg','svg');el.setAttribute('viewBox','0 0 24 24');el.setAttribute('aria-hidden','true');const p=doc.createElementNS(el.namespaceURI,'path');p.setAttribute('d',paths[name]||paths.panel);el.append(p);return el;}
    function button(label, glyph, run, text){const b=doc.createElement('button');b.type='button';b.title=label;b.setAttribute('aria-label',label);b.dataset.control=label;if(glyph)b.append(icon(glyph));if(text){const s=doc.createElement('span');s.textContent=text;b.append(s);}b.disabled=!host;b.onclick=()=>{if(ctx.mode==='preview'&&host)run?.();};return b;}
    function perform(action){return host.execute(action).then(ok=>{if(ok){open=null;}render();return ok;});}
    function closePopup(){open=null;render();}
    function toggle(name){open=open===name?null:name;render();}
    function fitPopup(){const pop=panel.querySelector('.popover');if(!pop)return;pop.style.left='';pop.style.right='0';pop.style.top='';pop.style.bottom='calc(100% + 12px)';const scale=root.getBoundingClientRect().width/Math.max(1,root.offsetWidth),r=pop.getBoundingClientRect(),p=panel.getBoundingClientRect(),view=doc.documentElement;const shift=Math.max(12-r.left,Math.min(0,view.clientWidth-12-r.right));pop.style.right=(-shift/Math.max(.01,scale))+'px';const above=p.top-24,below=view.clientHeight-p.bottom-24;const useBelow=above<160&&below>above;if(useBelow){pop.style.top='calc(100% + 12px)';pop.style.bottom='auto';}const list=pop.querySelector('.scene-list');if(list)list.style.maxHeight=Math.max(60,Math.min(300,((useBelow?below:above)/Math.max(.01,scale))-64))+'px';}
    let drag=null,suppressClick=false;
    panel.addEventListener('pointerdown',e=>{if(ctx.mode!=='preview'||!host||e.button!==0||e.target.closest('.popover'))return;suppressClick=false;(e.target.closest('button')||panel).setPointerCapture(e.pointerId);drag={x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false};});
    panel.addEventListener('pointermove',e=>{if(!drag)return;if(!drag.moved&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)<6)return;drag.moved=true;suppressClick=true;panel.setPointerCapture(e.pointerId);host.moveBy(e.clientX-drag.x,e.clientY-drag.y);drag.x=e.clientX;drag.y=e.clientY;});
    const endDrag=()=>{drag=null;};doc.addEventListener('pointerup',endDrag);doc.addEventListener('pointercancel',endDrag);
    panel.addEventListener('click',e=>{if(suppressClick){e.preventDefault();e.stopImmediatePropagation();suppressClick=false;}},true);
    function render(){
      if(disposed)return;
      const focus=root.getRootNode().activeElement?.dataset?.control;
      const state=host?host.read():{collapsed:false,scenes:[],progress:null,zoom:1,muted:false,fullscreen:false};
      const variant=(props.sceneStyles||{})[state.locationId]||{},p=Object.assign({},props,variant),style=Object.assign({},props.style,variant.style);
      const collapsed=!!state.collapsed; if(collapsed)open=null;
      root.style.width=collapsed?'52px':'100%';root.style.height=collapsed?'52px':'100%';
      panel.className='controller'+(collapsed?' collapsed':'')+(p.compact?' compact':'');
      const ink=style.textColor||'#f3eee0',paper=style.backgroundColor||'#252c3d',accent=style.accentColor||'#d9bf73';
      panel.style.setProperty('--ink',ink);panel.style.setProperty('--paper-solid',paper);panel.style.setProperty('--accent',accent);panel.style.setProperty('--accent-ink',/^#[0-9a-f]{6}$/i.test(accent)&&((parseInt(accent.slice(1,3),16)*299+parseInt(accent.slice(3,5),16)*587+parseInt(accent.slice(5,7),16)*114)/1000)<145?'#fff':'#172033');
      panel.style.setProperty('--paper','color-mix(in srgb,'+paper+' '+Math.round((style.backgroundOpacity??1)*100)+'%,transparent)');panel.style.setProperty('--radius',Math.max(0,style.cornerRadius??16)+'px');
      panel.style.backgroundImage=p.backgroundAssetId?'url("'+ctx.projectAssetUrl(p.backgroundAssetId)+'")':'none';panel.style.backgroundSize='cover';
      if(p.backgroundAssetId){const url=ctx.projectAssetUrl(p.backgroundAssetId);if(!loadedImages.has(url)){loadedImages.add(url);ctx.capture.waitUntil(new Promise((resolve,reject)=>{const image=new Image();image.onload=resolve;image.onerror=()=>reject(new Error('控制台背景素材加载失败'));image.src=url;}));}}
      panel.replaceChildren();
      const launcher=button(collapsed?'展开教师控制器':'收起教师控制器',null,()=>{open=null;host.setCollapsed(!collapsed);render();},collapsed?'展':'收');launcher.className='launcher';launcher.setAttribute('aria-expanded',String(!collapsed));
      if(p.collapsible!==false||collapsed)panel.append(launcher);
      if(collapsed)return;
      const identity=doc.createElement('div');identity.className='identity';identity.title='拖动教师控制台';const title=doc.createElement('strong');title.textContent=p.title||'教师控制台';identity.append(title);
      if(p.showSceneProgress!==false&&state.progress){const n=state.progress,progress=doc.createElement('span');progress.className='progress';progress.textContent=(n.sceneIndex+1)+' / '+n.sceneCount+' 页 · '+(n.stepIndex+1)+' / '+n.stepCount+' 步';identity.append(progress);const track=doc.createElement('div');track.className='track';const fill=doc.createElement('i');fill.style.width=((n.sceneIndex+1)/Math.max(1,n.sceneCount)*100)+'%';track.append(fill);identity.append(track);}
      panel.append(identity);
      const steps=doc.createElement('div');steps.className='group steps';const tools=doc.createElement('div');tools.className='group tools';panel.append(steps,tools);
      const specs=[...(p.buttons||[])];if(!specs.some(b=>b.action.type==='step.next'||b.action.type==='step.previous'))specs.unshift({id:'step-previous',label:'上一步',visible:true,action:{type:'step.previous'}},{id:'step-next',label:'下一步',visible:true,action:{type:'step.next'}});
      const glyphs={'step.previous':'left','step.next':'right','scene.previous':'previous','scene.next':'next','scene.open-picker':'list','scene.replay':'replay','course.restart':'replay','audio.toggle-mute':state.muted?'muted':'sound','player.fullscreen.toggle':'full'};
      for(const spec of specs){if(!spec.visible)continue;const type=spec.action.type,isNext=type==='step.next',isPicker=type==='scene.open-picker';const b=button(spec.label,glyphs[type],()=>isPicker?toggle('directory'):perform(spec.action),type.startsWith('step.')?spec.label:isPicker?'目录':!glyphs[type]?spec.label:undefined);b.dataset.controllerButtonId=spec.id;b.disabled=b.disabled||!host?.canExecute(spec.action);if(isPicker)b.setAttribute('aria-expanded',String(open==='directory'));if(type==='audio.toggle-mute')b.setAttribute('aria-pressed',String(state.muted));if(type==='player.fullscreen.toggle')b.setAttribute('aria-pressed',String(state.fullscreen));(type.startsWith('step.')?steps:tools).append(b);}
      const zoom=button('缩放',null,()=>toggle('zoom'),Math.round(state.zoom*100)+'%');zoom.setAttribute('aria-expanded',String(open==='zoom'));tools.append(zoom);
      if(open){const pop=doc.createElement('section');pop.className='popover';pop.setAttribute('role','dialog');pop.setAttribute('aria-label',open==='directory'?'场景目录':'缩放设置');const header=doc.createElement('header'),caption=doc.createElement('span');caption.textContent=open==='directory'?'场景目录':'视图缩放';header.append(caption,button('关闭面板','close',closePopup));pop.append(header);
        if(open==='directory'){const count=doc.createElement('small');count.textContent=state.scenes.length+' 页';caption.append(count);const list=doc.createElement('div');list.className='scene-list';for(const [i,scene] of state.scenes.entries()){const b=button(scene.name,null,()=>perform({type:'scene.go',sceneId:scene.id}));b.className='scene-row';const number=doc.createElement('em');number.textContent=String(i+1).padStart(2,'0');const label=doc.createElement('span');label.textContent=scene.name;b.append(number,label);if(scene.id===state.locationId)b.setAttribute('aria-current','page');list.append(b);}pop.append(list);
        }else{pop.style.width='240px';const row=doc.createElement('div');row.className='zoom-row';const value=doc.createElement('span');value.className='zoom-value';value.textContent=Math.round(state.zoom*100)+'%';row.append(button('缩小','minus',()=>host.setZoom(state.zoom-.25)),value,button('放大','plus',()=>host.setZoom(state.zoom+.25)));const reset=button('恢复默认视图',null,()=>host.resetView(),'恢复默认视图');reset.className='reset';pop.append(row,reset);}panel.append(pop);fitPopup();}
      if(focus)panel.querySelectorAll('button').forEach(b=>{if(b.dataset.control===focus)b.focus({preventScroll:true});});
    }
    const outside=e=>{if(open&&!e.composedPath().includes(root))closePopup();},escape=e=>{if(open&&e.key==='Escape'){e.preventDefault();closePopup();}};
    doc.addEventListener('pointerdown',outside,true);root.addEventListener('keydown',escape);doc.defaultView.addEventListener('resize',fitPopup);
    const observer=typeof ResizeObserver==='function'?new ResizeObserver(fitPopup):null;observer?.observe(root);
    const unsubscribe=host?host.subscribe(render):()=>{};render();
    return {updateProps(next){props=next;render();},resize(){render();},destroy(){disposed=true;doc.removeEventListener('pointerup',endDrag);doc.removeEventListener('pointercancel',endDrag);unsubscribe();observer?.disconnect();doc.removeEventListener('pointerdown',outside,true);root.removeEventListener('keydown',escape);doc.defaultView.removeEventListener('resize',fitPopup);panel.remove();css.remove();}};
  }
});`
