/* Standalone design prototype. No product APIs, model calls or real document writes. */
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const app=$('#app'), workspace=$('#workspace');
const initialTitle='把城市，\n变成一间自然教室。';
const pages=[{title:initialTitle,subtitle:'从一片叶子开始，重新认识每天经过的地方。',name:'从身边开始'},{title:'一片叶子，\n藏着多少个问题？',subtitle:'看形状，摸纹理，寻找叶脉。先说说你发现了什么。',name:'读懂一片叶'},{title:'把你的发现，\n讲给另一个人听。',subtitle:'画下来、写下来，让一次观察成为可以分享的经验。',name:'记录与分享'}];
const escapeHtml=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const defaultStates=()=>[{name:'初始显示',kind:'intro'},{name:'提出问题',kind:'question'},{name:'揭示线索',kind:'reveal'}];
pages.forEach(p=>{p.states=defaultStates();p.stateIndex=0});
let workspaceName='教学与创作',workspacePath='D:/创作空间';
let currentPage=0,currentFile='course',scope='城市自然观察',editor=false,preview=false,undoStack=[],toastTimer,workbenchPrefs=null;
const prefKey='guoling-design-v3-layout';
let prefs={dock:'right',left:true,chat:true,content:true,theme:'light',leftWidth:238,chatWidth:360};
try{Object.assign(prefs,JSON.parse(localStorage.getItem(prefKey)||'{}'))}catch{}
function hydrateIcons(root=document){root.querySelectorAll('[data-icon]').forEach(el=>{let name=el.dataset.icon;if(window.GL_ICONS?.[name])el.outerHTML=GL_ICONS[name]})}
function persist(){try{localStorage.setItem(prefKey,JSON.stringify(prefs))}catch{}}
function notice(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3000)}
function applyLayout(){workspace.dataset.dock=prefs.dock;app.classList.toggle('no-sidebar',!prefs.left);app.classList.toggle('no-chat',!prefs.chat);app.classList.toggle('no-content',!prefs.content);app.classList.toggle('dark',prefs.theme==='dark');$('#restoreChat').hidden=prefs.chat;$('#contentToggle span').textContent=prefs.content?'收起内容':'展开内容';document.documentElement.style.setProperty('--left-width',prefs.leftWidth+'px');document.documentElement.style.setProperty('--chat-width',prefs.chatWidth+'px');$$('[data-dock]').filter(x=>x.tagName==='BUTTON').forEach(b=>b.classList.toggle('active',b.dataset.dock===prefs.dock));persist()}
function toggleChat(){if(prefs.chat&&!prefs.content)prefs.content=true;prefs.chat=!prefs.chat;applyLayout()}
function toggleContent(){if(prefs.content&&!prefs.chat)prefs.chat=true;prefs.content=!prefs.content;applyLayout()}
function dialog(title,html){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=html;hydrateIcons($('#dialogBody'));$('#dialog').showModal()}
function saveUndo(){undoStack.push(structuredClone(pages))}
function showPage(n){currentPage=Math.max(0,Math.min(n,pages.length-1));const p=pages[currentPage];p.states??=defaultStates();p.stateIndex??=0;$('#slideTitle').innerText=p.title;$('#slideSubtitle').textContent=p.subtitle;$('#titleProperty').value=p.title;$('.slide-bottom b').textContent=String(currentPage+1).padStart(2,'0')+' / '+String(pages.length).padStart(2,'0');$$('[data-page]').forEach(b=>b.classList.toggle('active',Number(b.dataset.page)===currentPage));$('#pageCount').textContent=pages.length+' 个场景 · 当前 '+p.states.length+' 个状态';renderStates();}
function renderPages(){const items=pages.map((p,i)=>`<button class="film-item ${i===currentPage?'active':''}" data-page="${i}"><span class="mini-slide ${['green','cream','peach'][i%3]}">${escapeHtml(p.name)}</span><span>场景 ${String(i+1).padStart(2,'0')} <b>${escapeHtml(p.name)}</b></span></button>`);$('#pageList').innerHTML=pages.map((p,i)=>`<div class="scene-tree-group">${items[i]}<div class="scene-states">${(p.states||defaultStates()).map((state,j)=>`<button class="tree-state" data-scene="${i}" data-state="${j}">${j+1} · ${escapeHtml(state.name)}</button>`).join('')}</div></div>`).join('');$('#filmstrip').innerHTML='<span class="strip-label">场景</span>'+items.join('')+'<button class="add-page film-add" aria-label="添加场景"><i data-icon="plus"></i></button>';hydrateIcons($('#filmstrip'));$$('[data-page]').forEach(b=>b.onclick=()=>{openFile('course');showPage(Number(b.dataset.page))});$$('.tree-state').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.scene);pages[i].stateIndex=Number(b.dataset.state);showPage(i)});$$('.add-page').forEach(b=>b.onclick=()=>{saveUndo();pages.push({title:'新的观察，\n从这里开始。',subtitle:'点击文字，写下你的想法。',name:'新的观察',states:defaultStates(),stateIndex:0});renderPages();showPage(pages.length-1);notice('已在原型中添加一个场景')});}
function renderStates(){const p=pages[currentPage],state=p.states[p.stateIndex];$('#stateStrip').hidden=currentFile!=='course';$('#stateStrip').innerHTML='<span class="strip-label">状态 <small>'+escapeHtml(p.name)+'</small></span><div class="state-buttons">'+p.states.map((s,i)=>`<button class="state-button ${i===p.stateIndex?'active':''}" data-current-state="${i}"><span>${String(i+1).padStart(2,'0')}</span>${escapeHtml(s.name)}</button>`).join('')+'</div><button class="icon-button small" id="manageStates" aria-label="管理当前场景状态" title="新增、重命名与排序"><i data-icon="square-pen"></i></button>';hydrateIcons($('#stateStrip'));$$('[data-current-state]').forEach(b=>b.onclick=()=>{p.stateIndex=Number(b.dataset.currentState);renderStates()});$('#manageStates').onclick=manageStates;$$('.tree-state').forEach(b=>b.classList.toggle('active',Number(b.dataset.scene)===currentPage&&Number(b.dataset.state)===p.stateIndex));$('#stageLabel').textContent='场景 '+(currentPage+1)+' · '+p.name+' / 状态 '+(p.stateIndex+1)+' · '+state.name;$('#contextChip').innerHTML='<i data-icon="mouse-pointer-2"></i>'+escapeHtml(p.name)+' / '+escapeHtml(state.name)+'<i data-icon="x"></i>';hydrateIcons($('#contextChip'));$('#inspectorState').textContent=(p.stateIndex+1)+' / '+p.states.length+' · '+state.name;const content=state.kind==='question'?[['?','先描述，再解释','你看见了哪些不同？'],['01','形状与边缘','选一片叶子仔细观察'],['02','写下你的推测','暂不揭示参考答案']]:state.kind==='reveal'?[['01','看形状','针形、掌形与卵形'],['02','摸边缘','平滑、锯齿与波浪'],['03','找叶脉','用观察解释你的判断']]:[['01','走近一棵树','发现身边的线索'],['02','读懂一片叶','把观察变成问题'],['03','记录一个发现','让经验成为知识']];$('.field-index').innerHTML=content.map(x=>'<div><span>'+x[0]+'</span><p>'+x[1]+'<small>'+x[2]+'</small></p></div>').join('');$('#slide').dataset.state=state.kind;$('#pageCount').textContent=pages.length+' 个场景 · 当前 '+p.states.length+' 个状态';}
function manageStates(){const p=pages[currentPage];dialog('场景状态 · '+p.name,'<p>状态属于当前场景；切换状态不会创建新场景。</p><div class="state-manager">'+p.states.map((s,i)=>`<div><input aria-label="状态 ${i+1} 名称" data-state-name="${i}" value="${escapeHtml(s.name)}"><button data-state-up="${i}" ${i===0?'disabled':''}>上移</button><button data-state-down="${i}" ${i===p.states.length-1?'disabled':''}>下移</button></div>`).join('')+'</div><button class="outline" id="newState">添加状态</button> <button class="primary" id="finishStates">完成</button>');$$('[data-state-name]').forEach(input=>input.onchange=()=>{saveUndo();p.states[Number(input.dataset.stateName)].name=input.value.trim()||'未命名状态';renderPages();renderStates()});const move=(i,to)=>{saveUndo();const selected=p.states[p.stateIndex];[p.states[i],p.states[to]]=[p.states[to],p.states[i]];p.stateIndex=p.states.indexOf(selected);$('#dialog').close();renderPages();renderStates();manageStates()};$$('[data-state-up]').forEach(b=>b.onclick=()=>move(+b.dataset.stateUp,+b.dataset.stateUp-1));$$('[data-state-down]').forEach(b=>b.onclick=()=>move(+b.dataset.stateDown,+b.dataset.stateDown+1));$('#newState').onclick=()=>{saveUndo();p.states.push({name:'新状态',kind:'question'});p.stateIndex=p.states.length-1;$('#dialog').close();renderPages();renderStates();manageStates()};$('#finishStates').onclick=()=>$('#dialog').close();}
const docViews={
 document:`<div class="doc-eyebrow">PROJECT NOTES / 城市自然观察</div><div contenteditable="true" aria-label="活动策划正文"><h2>让城市成为一间自然教室</h2><p>一份从真实观察出发的活动策划。</p><blockquote>先让学生看见，再让他们提问，最后把发现连成知识。</blockquote><h3>01　从身边的一棵树开始</h3><p>请每组选择一棵树，观察它与周围环境的关系。暂不提供名称，让学生描述自己真正看见的特征。</p><h3>02　把观察变成问题</h3><p>比较叶片的形状、边缘和叶脉。每组选出一个最想知道答案的问题，并用观察记录支持自己的推测。</p><h3>03　留下可以分享的发现</h3><p>用文字、图画或照片记录发现。分享时，说明观察依据，以及还需要验证的部分。</p></div>`,
 material:`<div class="doc-eyebrow">参考资料 · PDF 阅读</div><h2>城市树木观察手册</h2><p>第 8 页 / 叶片的观察</p><blockquote>观察不仅是看见一个名称，而是发现它与其他事物的不同。</blockquote><h3>三个观察线索</h3><p><b>形状</b>　叶片可能是针形、掌形或卵形。先用自己的语言描述，再尝试归类。</p><p><b>边缘</b>　仔细观察边缘是否有锯齿、波浪或分裂。</p><p><b>叶脉</b>　对着光，寻找叶脉的走向与连接方式。</p><p class="doc-eyebrow">设计示例 · 此页为只读资料预览</p>`,
 notes:`<div class="doc-eyebrow">FIELD NOTES / 观察记录</div><div contenteditable="true" aria-label="观察记录正文"><h2>实地观察记录</h2><p>地点：学校东侧的小花园</p><h3>今天看见了什么？</h3><p>同一棵树上，不同位置的叶子颜色有差异。靠近外侧的叶片更亮，内侧的叶片颜色更深。</p><h3>还想知道什么？</h3><p>叶片颜色和阳光照射的时间有关系吗？下次在相同位置继续记录。</p></div>`,
 office:`<div class="doc-eyebrow">PPTX / 专业宿主接续</div><h2>校园活动介绍</h2><p>观察身边的自然，建立与城市的连接。</p><blockquote>四周的自然观察计划<br>每周一次 · 每次一个问题</blockquote><p>作品的基础内容可以在工作台查看。母版、复杂动画等专业操作，在对应宿主中继续。</p><button class="primary" id="openHost">在 PowerPoint / WPS 中打开</button><p class="doc-eyebrow">设计演示：不会启动或写入真实 Office 文件</p>`,
 data:`<div class="doc-eyebrow">CSV / 观察清单</div><h2>观察从记录开始</h2><table><thead><tr><th>地点</th><th>观察对象</th><th>记录状态</th></tr></thead><tbody><tr><td>校园东侧</td><td contenteditable="true">银杏树</td><td>已记录</td></tr><tr><td>街角花园</td><td contenteditable="true">梧桐树</td><td>待观察</td></tr><tr><td>河边步道</td><td contenteditable="true">柳树</td><td>待观察</td></tr></tbody></table><p class="doc-eyebrow">可点击对象单元格体验编辑</p>`
};
function openFile(file){currentFile=file;prefs.content=true;setPreview(false);$('#previewButton').hidden=!['course','office'].includes(file);$('#stateStrip').hidden=file!=='course';if(editor&&file!=='course')setEditor(false);$('#slide').hidden=file!=='course';$('#documentPage').hidden=file==='course';$('#filmstrip').hidden=file!=='course';$('#formatTools').hidden=file!=='course';$('#stage').classList.toggle('document-stage',file!=='course');$('#stageHint').textContent=file==='course'?'点击文字直接编辑':file==='material'?'参考资料 · 只读预览':'正文与选区 · 就地修改';$('#contentType').textContent=file==='course'?'原生互动作品':file==='office'?'Office 文件':file==='material'?'PDF 参考资料':'项目文件';$$('[data-file]').forEach(b=>{b.classList.toggle('selected',b.dataset.file===file);if(b.classList.contains('file-tab'))b.classList.toggle('active',b.dataset.file===file)});if(file!=='course'){$('#documentPage').innerHTML=docViews[file]||docViews.document;$('#documentPage').querySelectorAll('[contenteditable]').forEach(e=>e.addEventListener('input',()=>$('#saveStatus').innerHTML='原型内已更改'));if($('#openHost'))$('#openHost').onclick=hostDialog}$('#editorToggle').disabled=false;$('#editorToggle span').textContent=file!=='course'?'在专业宿主中打开':editor?'返回工作台':'在编辑器中打开';if(file==='material')$('#editButton').textContent='阅读';else $('#editButton').textContent='编辑';if(file==='course')renderStates();applyLayout()}
function setEditor(value){if(value&&!editor)workbenchPrefs={...prefs};editor=value;app.classList.toggle('editor',editor);$('#editorToggle span').textContent=editor?'返回工作台':'在编辑器中打开';$('#workEyebrow').textContent=editor?'GUOLING EDITOR / 原生互动':'WORKSPACE / '+scope;$('#workTitle').innerHTML=editor?'城市自然观察<span class="title-dot"></span>':'一起完成这堂自然课<span class="title-dot"></span>';if(editor){prefs.content=true;prefs.chat=false;prefs.dock='right';}else if(workbenchPrefs){Object.assign(prefs,workbenchPrefs);prefs.content=true;}applyLayout();notice(editor?'已进入原生编辑器 · 当前内容与修改保持不变':'已返回工作台 · 继续同一份作品')}
function hostDialog(){const md=['document','notes'].includes(currentFile),office=['office','data'].includes(currentFile);const options=md?['系统默认 Markdown 编辑器','Typora','Visual Studio Code','其他编辑器…']:office?[currentFile==='office'?'Microsoft PowerPoint':'Microsoft Excel','WPS Office','其他常用编辑器…']:['系统默认 PDF 阅读器','其他编辑器…'];dialog('选择专业宿主','<p>'+ (md?'Markdown 同样可以在专业编辑器中继续工作。':'为当前文件选择对应的专业宿主。')+'</p><div class="dialog-list">'+options.map(label=>'<button data-host="'+escapeHtml(label)+'">'+escapeHtml(label)+'</button>').join('')+'</div>'+(office?'<p class="future-host">果铃原生 Office 编辑器 · 长期规划<br>开发完成后作为默认宿主，目前不可选择。</p>':'')+'<p>仅演示入口，不启动软件、不修改真实文件。</p>');$$('[data-host]').forEach(b=>b.onclick=()=>{$('#dialog').close();notice('已选择 '+b.dataset.host+'（设计演示）')});}
function setScope(name){scope=name;$('#workEyebrow').textContent=workspaceName+' / '+(name==='整个工作空间'?'工作空间会话':name);$('#footerScope').textContent=workspacePath+(name==='整个工作空间'?'':'/'+name);$('.composer-foot span').textContent='优先目录：'+(name==='整个工作空间'?'工作空间根目录':name+'/');$$('[data-project]').forEach(b=>b.classList.toggle('active',b.dataset.project===name));notice(name==='整个工作空间'?'使用工作空间根目录':'优先使用与输出到 '+name+'/；仍可引用整个工作空间');}
$('#leftToggle').onclick=()=>{prefs.left=!prefs.left;applyLayout()};$('#contentToggle').onclick=toggleContent;$('#chatToggle').onclick=toggleChat;$('#showChat').onclick=toggleChat;$('#themeToggle').onclick=()=>{prefs.theme=prefs.theme==='light'?'dark':'light';applyLayout()};$('#editorToggle').onclick=()=>currentFile!=='course'?hostDialog():setEditor(!editor);$('#focusButton').onclick=()=>{prefs.chat=!prefs.chat;prefs.left=prefs.chat;applyLayout()};$('#layoutButton').onclick=()=>$('#layoutMenu').hidden=!$('#layoutMenu').hidden;$('#menuSidebar').onclick=$('#leftToggle').onclick;$('#menuChat').onclick=toggleChat;$('#menuContent').onclick=toggleContent;$$('button[data-dock]').forEach(b=>b.onclick=()=>{prefs.dock=b.dataset.dock;applyLayout();$('#layoutMenu').hidden=true});document.addEventListener('click',e=>{if(!e.target.closest('#layoutMenu')&&!e.target.closest('#layoutButton'))$('#layoutMenu').hidden=true});$('#resetLayout').onclick=()=>{prefs={dock:'right',left:true,chat:true,content:true,theme:'light',leftWidth:238,chatWidth:360};applyLayout();notice('已恢复默认布局')};$$('[data-collapse]').forEach(b=>b.onclick=()=>{const panel=$('#'+b.dataset.collapse);panel.hidden=!panel.hidden;b.setAttribute('aria-expanded',String(!panel.hidden))});$$('[data-file]').forEach(b=>b.onclick=()=>openFile(b.dataset.file));$$('[data-project]').forEach(b=>b.onclick=()=>setScope(b.dataset.project));$('#workspaceScope').onclick=()=>setScope('整个工作空间');$$('[data-session]').forEach(b=>b.onclick=()=>{$$('[data-session]').forEach(x=>x.classList.toggle('active',x===b));$('#workTitle').textContent=b.dataset.session;notice('已切换示例会话：'+b.dataset.session)});
$('#scopeButton').onclick=()=>{dialog('切换工作空间','<p>工作空间是独立的根目录与授权范围。项目在左侧切换。</p><div class="dialog-list"><button data-workspace="teaching">教学与创作<small>D:/创作空间</small></button><button data-workspace="client">客户方案<small>E:/客户工作空间</small></button><button id="chooseWorkspace">选择其他工作空间文件夹…</button></div><div class="permission-note"><strong>工作空间权限</strong><p>范围内：AI 默认拥有完整权限。<br>范围外：默认只读，写入、执行等操作需另行授权。</p></div><p>这是权限设计说明，原型没有实际授权或文件访问能力。</p>');$$('[data-workspace]').forEach(b=>b.onclick=()=>{$('#dialog').close();switchWorkspace(b.dataset.workspace)});$('#chooseWorkspace').onclick=()=>notice('正式产品将在此打开根目录选择器；原型不申请文件权限')};
$('#newProject').onclick=()=>{dialog('添加项目文件夹','<p>将工作空间中的文件夹作为项目管理。资料优先从这里读取，新产物默认放在这里；仍可使用工作空间内其他文件。</p><input id="projectName" aria-label="工作空间内的项目文件夹" placeholder="例如：新课例"><button class="primary" id="createProject">添加文件夹项目</button>');$('#createProject').onclick=()=>{const name=$('#projectName').value.trim();if(!name)return;if(/[\\/:]/.test(name)||name==='..'){notice('原型请输入一个工作空间内的文件夹名称');return;}const group=document.createElement('details');group.className='project-group';group.open=true;group.innerHTML='<summary><button class="project-row" data-project="'+escapeHtml(name)+'"><i data-icon="folder"></i>'+escapeHtml(name)+'</button></summary><div class="folder-empty">尚无会话，点击“新对话”开始</div>';$('#projectGroups').append(group);const folder=document.createElement('details');folder.innerHTML='<summary>'+escapeHtml(name)+'</summary><div class="folder-empty">空文件夹</div>';$('#resources').append(folder);bindNavigation();setScope(name);$('#dialog').close()}};
$('#closeDialog').onclick=()=>$('#dialog').close();$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog'))$('#dialog').close()});$('#helpButton').onclick=()=>dialog('果铃 · 新版设计原型','<p>可以体验：资源与会话独立收展、拖动分隔线、调整内容位置、打开文档、直接改字，以及切换原生编辑器。</p><p>布局偏好保存在本浏览器；示例内容修改仅在本次页面中保留。此原型不连接模型、不写入真实文件。</p><p><a href="../00-设计说明.md" target="_blank">打开 V3 设计说明 →</a></p>');
$('#newTask').onclick=()=>{$('#messages').innerHTML='<div class="empty-chat"><div class="eyebrow">A LITTLE IDEA, A NEW POSSIBILITY</div><h2>从一个想法开始。</h2><p>描述你想完成的事，或从左侧打开一份文件。</p><div class="empty-actions"><button class="outline" id="emptyMaterials">整理一组资料</button><button class="outline" id="emptyCreate">创作一个作品</button></div></div>';$('#workTitle').textContent='新的对话';prefs.content=false;prefs.chat=true;applyLayout();$('#emptyMaterials').onclick=()=>{$('#prompt').value='帮我整理这些资料，提炼可以用于创作的内容。';$('#prompt').focus()};$('#emptyCreate').onclick=()=>{$('#prompt').value='我想创作一个互动作品。';$('#prompt').focus()}};
function appendMessage(text,cls){const el=document.createElement('div');el.className=cls;el.textContent=text;$('#messages').append(el);el.scrollIntoView({block:'end'})}
$('#chatForm').onsubmit=e=>{e.preventDefault();const text=$('#prompt').value.trim();if(!text)return;appendMessage(text,'user-message');$('#prompt').value='';const el=document.createElement('div');el.className='assistant-message prototype-response';el.innerHTML='<div class="assistant-name"><span class="mini-brand">果</span>果铃<span>交互演示</span></div><p>这条需求将针对当前选定的内容执行。</p><p class="secondary">原型不会调用模型。你可以继续打开作品、直接修改文字，或调整布局。</p><button class="outline">打开当前作品</button>';el.querySelector('button').onclick=()=>openFile('course');$('#messages').append(el);el.scrollIntoView({block:'end'})};$('#prompt').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();$('#chatForm').requestSubmit()}};
$('#openResult').onclick=()=>openFile('course');$('#contextChip').onclick=()=>{$('#contextChip').hidden=true;notice('已移除本轮引用；当前打开的文件不受影响')};const sourceDialog=()=>{dialog('本次采用的资料','<div class="dialog-list"><button id="sourcePdf"><i data-icon="file-text"></i>城市树木观察手册.pdf<small>事实参考</small></button><button id="sourceMd"><i data-icon="file-text"></i>实地观察记录.md<small>活动素材</small></button></div>');$('#sourcePdf').onclick=()=>{$('#dialog').close();openFile('material')};$('#sourceMd').onclick=()=>{$('#dialog').close();openFile('notes')}};$('#sourceChip').onclick=sourceDialog;$('#showSources').onclick=sourceDialog;$('#attachButton').onclick=()=>{dialog('添加到本轮对话','<p>从整个工作空间选择资料，优先展示项目文件夹中的内容。不会改变被修改的目标文件。</p><div class="dialog-list"><label><input type="checkbox" checked> 共享资料 / 城市树木观察手册.pdf</label><label><input type="checkbox" checked> 实地观察记录.md</label><label><input type="checkbox"> 活动策划.md</label></div><button class="primary" id="attachConfirm">采用所选资料</button>');$('#attachConfirm').onclick=()=>{const count=$$('#dialogBody input:checked').length;$('#sourceChip').innerHTML='<i data-icon="paperclip"></i>'+count+' 份资料';hydrateIcons($('#sourceChip'));$('#dialog').close();notice('已更新本轮资料引用')}};
$('#modelButton').onclick=()=>dialog('本轮创作设置','<p>Codex · Luna · Fast</p><p>模型与速度设置在这里查看。设计原型不会发起真实模型任务。</p>');$('#changesButton').onclick=()=>dialog('本次修改','<p>创建 3 个场景，每个场景包含多个状态；采用手册中的叶片观察方法；保留学生先观察、后解释的过程。</p><p>原型中的标题和说明支持直接编辑。进入编辑器后会保留这些修改。</p>');$('#undoButton').onclick=()=>{if(!undoStack.length){notice('没有新的本地修改可以撤销');return;}const previous=undoStack.pop();pages.splice(0,pages.length,...previous);renderPages();showPage(Math.min(currentPage,pages.length-1));notice('已撤销上一项本地修改')};
$('#slideTitle').addEventListener('focus',saveUndo);$('#slideTitle').oninput=()=>{pages[currentPage].title=$('#slideTitle').innerText;$('#titleProperty').value=pages[currentPage].title;$('#saveStatus').innerHTML='原型内已更改'};$('#slideSubtitle').addEventListener('focus',saveUndo);$('#slideSubtitle').oninput=()=>{pages[currentPage].subtitle=$('#slideSubtitle').innerText;$('#saveStatus').innerHTML='原型内已更改'};$('#titleProperty').addEventListener('focus',saveUndo);$('#titleProperty').oninput=()=>{pages[currentPage].title=$('#titleProperty').value;$('#slideTitle').innerText=pages[currentPage].title};$('#fontSize').onchange=e=>{$('#slideTitle').style.fontSize=Number(e.target.value)/7.2+'cqw';$('#propertySize').value=e.target.value};$('#propertySize').onchange=e=>{$('#slideTitle').style.fontSize=Number(e.target.value)/7.2+'cqw'};$('#propertyWeight').onchange=e=>$('#slideTitle').style.fontWeight=e.target.value;$('#boldButton').onclick=()=>$('#slideTitle').style.fontWeight=$('#slideTitle').style.fontWeight==='700'?'400':'700';const recolor=()=>{$('#slideTitle').style.color=$('#slideTitle').style.color==='rgb(153, 100, 61)'?'#173f35':'#99643d'};$('#colorButton').onclick=recolor;$('#propertyColor').onclick=recolor;
function setPreview(value){preview=value&&['course','office'].includes(currentFile);app.classList.toggle('preview',preview);$('#slideTitle').contentEditable=String(!preview);$('#slideSubtitle').contentEditable=String(!preview);$('#editButton').classList.toggle('active',!preview);$('#previewButton').classList.toggle('active',preview);$('#stageHint').textContent=preview?'试运行中 · 点击开始观察推进当前状态，再进入下一场景':'点击文字直接编辑'}$('#previewButton').onclick=()=>{if(currentFile==='office'){dialog('PPT 试运行','<p>从当前幻灯片开始播放。正式产品使用对应演示能力；本原型仅表达 PPT 的试运行入口。</p>');return;}setPreview(true)};$('#editButton').onclick=()=>setPreview(false);$('#startLesson').onclick=()=>{if(!preview){notice('先切换到试运行，即可体验页面跳转');return}const p=pages[currentPage];if(p.stateIndex<p.states.length-1){p.stateIndex++;renderStates()}else showPage((currentPage+1)%pages.length)};$('#zoomButton').onclick=()=>{const large=$('#slide').style.maxWidth==='none';$('#slide').style.maxWidth=large?'900px':'none';notice('画布已适应当前区域')};
$$('[data-layer]').forEach(b=>b.onclick=()=>{$$('[data-layer]').forEach(x=>x.classList.toggle('active',b===x));notice('已选中：'+b.textContent.trim());if(b.dataset.layer==='title')$('#slideTitle').focus();if(b.dataset.layer==='subtitle')$('#slideSubtitle').focus()});$$('[data-inspect]').forEach(b=>b.onclick=()=>{if(b.dataset.inspect==='属性'){notice('属性位于当前右侧面板');return;}dialog(b.dataset.inspect+'编辑',b.dataset.inspect==='交互'?'<p>点击“开始观察” → 切换至“读懂一片叶”。</p><p>完整编辑器在此管理触发条件、动作与目标。当前原型的试运行已经演示该跳转。</p>':'<p>组件库位于完整编辑器中，可插入已有互动组件并调整其开放参数。</p><p>这张设计稿暂不模拟组件编译与运行。</p>')});$('#addStep').onclick=manageStates;$('#exportButton').onclick=()=>dialog('交付当前作品','<div class="dialog-list"><button id="downloadDemo"><i data-icon="download"></i>下载活动策划示例<small>Markdown</small></button><button id="exportHtml"><i data-icon="globe"></i>导出互动 HTML<small>产品能力入口</small></button></div><p>设计原型只提供示例文档下载，不生成真实课件工程。</p>');document.addEventListener('click',e=>{if(e.target.closest('#downloadDemo')){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(['# 城市自然观察\n\n'+pages.map(p=>'## '+p.name+'\n'+p.title+'\n'+p.subtitle).join('\n\n')],{type:'text/markdown;charset=utf-8'}));a.download='城市自然观察-设计示例.md';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}if(e.target.closest('#exportHtml'))notice('此处演示交付入口，未连接真实课件导出')});
function resizeHandle(el,kind){el.onpointerdown=e=>{el.setPointerCapture(e.pointerId);const startX=e.clientX,startY=e.clientY,base=kind==='sidebar'?prefs.leftWidth:prefs.chatWidth,baseHeight=$('#conversation').getBoundingClientRect().height;el.onpointermove=ev=>{if(kind==='sidebar'){prefs.leftWidth=Math.max(180,Math.min(360,base+ev.clientX-startX));}else if(['top','bottom'].includes(prefs.dock)){let dy=(ev.clientY-startY)*(prefs.dock==='top'?-1:1);$('#conversation').style.height=Math.max(165,Math.min(380,baseHeight+dy))+'px';}else{prefs.chatWidth=Math.max(265,Math.min(560,base+(ev.clientX-startX)*(prefs.dock==='left'?-1:1)));}applyLayout()};el.onpointerup=()=>{el.onpointermove=null;persist()}};el.onkeydown=e=>{if(e.key!=='ArrowLeft'&&e.key!=='ArrowRight')return;e.preventDefault();let delta=e.key==='ArrowRight'?20:-20;if(kind==='sidebar')prefs.leftWidth=Math.max(180,Math.min(360,prefs.leftWidth+delta));else prefs.chatWidth=Math.max(265,Math.min(560,prefs.chatWidth+delta));applyLayout()}}
function bindNavigation(){hydrateIcons();$$('[data-file]').forEach(b=>b.onclick=()=>openFile(b.dataset.file));$$('[data-project]').forEach(b=>b.onclick=()=>setScope(b.dataset.project));$$('[data-session]').forEach(b=>b.onclick=()=>{setScope(b.dataset.projectSession||'整个工作空间');$$('[data-session]').forEach(x=>x.classList.toggle('active',x===b));$('#workTitle').textContent=b.dataset.session;});}
const teachingExplorer=$('#resources').innerHTML,teachingProjects=$('#projectGroups').innerHTML;
function switchWorkspace(key){if(editor)setEditor(false);const teaching=key==='teaching';workspaceName=teaching?'教学与创作':'客户方案';workspacePath=teaching?'D:/创作空间':'E:/客户工作空间';$('#scopeName').textContent=workspaceName;$('#resources').innerHTML=teaching?teachingExplorer:'<div class="workspace-root">E:/客户工作空间</div><div class="folder-empty">新工作空间 · 暂无文件</div>';$('#projectGroups').innerHTML=teaching?teachingProjects:'<div class="folder-empty">可将此工作空间中的文件夹添加为项目</div>';$('#workspaceSessions').innerHTML='<button class="session-row" data-project-session="整个工作空间" data-session="新的工作空间会话">新的工作空间会话</button>';bindNavigation();setScope('整个工作空间');$('#newTask').click();$('#contentToggle').disabled=!teaching;$('#editorToggle').disabled=!teaching;$('#rightToggle').disabled=!teaching;notice('已切换独立工作空间：'+workspacePath+'（示例）');}
bindNavigation();
resizeHandle($('#sidebarResize'),'sidebar');resizeHandle($('#paneResize'),'pane');renderPages();hydrateIcons();showPage(0);applyLayout();const params=new URLSearchParams(location.search);if(params.get('dock')){prefs.dock=params.get('dock');applyLayout()}if(params.get('view')==='editor')setEditor(true);if(params.get('view')==='focus'){prefs.chat=false;prefs.left=false;applyLayout()}if(params.get('view')==='task')$('#newTask').click();
function fitSlide(){if(currentFile!=='course'||!prefs.content)return;const stage=$('#stage'),style=getComputedStyle(stage);const availableWidth=stage.clientWidth-parseFloat(style.paddingLeft)-parseFloat(style.paddingRight);const availableHeight=stage.clientHeight-parseFloat(style.paddingTop)-parseFloat(style.paddingBottom)-$('#stageLabel').parentElement.offsetHeight-$('.stage-bottom').offsetHeight;$('#slide').style.width=Math.max(220,Math.min(availableWidth,availableHeight*1.55))+'px';$('#slide').style.alignSelf='center'}
new ResizeObserver(fitSlide).observe($('#stage'));fitSlide();
// Panel chrome stays consistent across the two native work positions.
const rightToggle=document.createElement('button');rightToggle.className='icon-button';rightToggle.id='rightToggle';rightToggle.setAttribute('aria-label','收展右侧栏');rightToggle.title='收展右侧栏';rightToggle.innerHTML='<i data-icon="panel-right"></i>';$('#layoutButton').before(rightToggle);hydrateIcons(rightToggle);rightToggle.onclick=()=>{if(editor){app.classList.toggle('no-inspector');fitSlide()}else toggleContent()};$('#leftToggle').onclick=()=>{if(editor){app.classList.toggle('no-page-nav');fitSlide()}else{prefs.left=!prefs.left;applyLayout()}};$('#menuSidebar').onclick=$('#leftToggle').onclick;
$('#documentPage').addEventListener('input',()=>{if(currentFile!=='course'&&currentFile!=='material')docViews[currentFile]=$('#documentPage').innerHTML});
