import type { ReactNode } from 'react'
import type { LessonConversation, LessonWorkspace } from '../../../shared/lessonWorkspace'
import type { LessonDesktopRequest, LessonDesktopResult, LessonDirectoryEntry } from '../../../shared/lessonDesktopContract'
import { LessonDocumentEditor } from '../../documentFiles/LessonDocumentEditor'
import type { RecoverableDocumentFilePort } from '../../documentFiles/documentFileSession'
import type { DocumentChatTarget } from '../../documentFiles/documentAiTaskController'
import { LessonConversationNavigation } from '../LessonConversationNavigation'
import type { DocumentTabsController, LessonFileTab } from '../controller/useDocumentTabsController'
import { LessonDirectoryTree } from './LessonDirectoryTree'

export interface LessonWorkspaceViewProps {
  state: {
    workspace: string | null; standalone: boolean; recent: string[]; selectedDirectory: string | null; lessons: LessonWorkspace[]; lesson: LessonWorkspace | null; conversations: LessonConversation[]; conversation: LessonConversation | null; name: string; creating: boolean; openingCopy: boolean; error: string | null; busy: boolean; treeVersion: number; explorerOpen: boolean; conversationsOpen: boolean; workflowOpen: boolean; mobilePane: 'navigation' | 'chat' | 'workbench'
  }
  actions: {
    run(action: () => Promise<void>): Promise<void>; openWorkspace(directory?: string, create?: boolean): Promise<void>; activate(lesson: LessonWorkspace, conversation?: LessonConversation): Promise<void>; selectConversation(conversation: LessonConversation): Promise<void>; openLesson(asCopy?: boolean): Promise<void>; createLesson(): Promise<void>; openFile(entry: LessonDirectoryEntry): Promise<void>; newStandaloneProject(): Promise<void>; setSelectedDirectory(value: string | null): void; setName(value: string): void; setCreating(value: boolean): void; setOpeningCopy(value: boolean): void; refreshTree(): void; setExplorerOpen(value: boolean): void; setConversationsOpen(value: boolean): void; setWorkflowOpen(value: boolean): void; setMobilePane(value: 'navigation' | 'chat' | 'workbench'): void; setConversations(value: LessonConversation[]): void; clearConversation(): void
  }
  operation(request: LessonDesktopRequest): Promise<LessonDesktopResult>
  documentPort: RecoverableDocumentFilePort
  tabs: DocumentTabsController
  projectPath: string | null
  renderChat(lesson: LessonWorkspace, conversation: LessonConversation, documentTarget?: DocumentChatTarget): ReactNode
  renderMaterial?(path: string, lesson: LessonWorkspace | null): ReactNode
  renderMaterials?(lesson: LessonWorkspace): ReactNode
  renderWorkflow?(lesson: LessonWorkspace, conversation: LessonConversation): ReactNode
  children: ReactNode
}

const basename = (path: string) => path.replace(/[\\/]$/, '').split(/[\\/]/).pop() || path
const join = (directory: string, name: string) => `${directory.replace(/[\\/]$/, '')}/${name}`
function relativeFile(lesson: LessonWorkspace, filename: string) {
  const root = lesson.identity.normalizedDirectory.replace(/[\\/]$/, '')
  const lower = (value: string) => value.replace(/\\/g, '/').toLowerCase()
  return lower(filename).startsWith(`${lower(root)}/`) ? filename.replace(/\\/g, '/').slice(root.length + 1) : null
}

export function LessonWorkspaceView(props: LessonWorkspaceViewProps) {
  const { state, actions, tabs } = props
  const workspaceName = state.workspace ? basename(state.workspace) : ''
  return <div className="lesson-workspace-shell">
    <header className="lesson-workspace-toolbar">
      <div className="lesson-workspace-identity">{state.workspace ? <><span>工作空间</span><strong title={state.workspace}>{workspaceName}</strong>{state.lesson && <><span aria-hidden="true">/</span><strong title={state.lesson.identity.normalizedDirectory}>{state.lesson.manifest.title}</strong></>}</> : <strong>课例创作</strong>}</div>
      <div className="lesson-workspace-toolbar-actions"><button type="button" className="lesson-primary-action" disabled={state.busy} onClick={() => actions.setCreating(true)}>新建课例</button><button type="button" disabled={state.busy} onClick={() => { void actions.run(() => actions.openWorkspace()) }}>切换工作空间</button><details className="lesson-workspace-more"><summary>更多</summary><button type="button" disabled={state.busy} onClick={() => { void actions.run(() => actions.openWorkspace(undefined, true)) }}>新建工作空间</button><button type="button" disabled={state.busy} onClick={() => { void actions.run(actions.newStandaloneProject) }}>新建独立课件</button></details></div>
    </header>
    {state.error && <div role="alert" className="lesson-workspace-error">{state.error}</div>}
    {!state.workspace && !state.standalone && <section className="lesson-workspace-landing"><p className="lesson-eyebrow">从真实文件夹开始</p><h2>创建一份可保存、可重开的课例</h2><p>先选择工作空间；随后在其中建立独立课例，整理材料、审阅文档并制作课件。</p><div><button type="button" className="lesson-primary-action" disabled={state.busy} onClick={() => { void actions.run(() => actions.openWorkspace()) }}>打开工作空间</button><button type="button" disabled={state.busy} onClick={() => { void actions.run(() => actions.openWorkspace(undefined, true)) }}>新建工作空间</button></div>{state.recent.length > 0 && <div className="lesson-recent-workspaces"><h3>最近使用</h3>{state.recent.map(directory => <button type="button" title={directory} key={directory} onClick={() => { void actions.run(() => actions.openWorkspace(directory)) }}>{basename(directory)}</button>)}</div>}</section>}
    <div className="lesson-workspace-columns" data-active-pane={state.mobilePane} hidden={!state.workspace && !state.standalone}>
      {state.workspace && <div className="lesson-workspace-pane-switcher" role="tablist" aria-label="工作台区域"><button type="button" role="tab" aria-selected={state.mobilePane === 'navigation'} onClick={() => actions.setMobilePane('navigation')}>资源与课例</button><button type="button" role="tab" aria-selected={state.mobilePane === 'chat'} onClick={() => actions.setMobilePane('chat')}>对话</button><button type="button" role="tab" aria-selected={state.mobilePane === 'workbench'} onClick={() => actions.setMobilePane('workbench')}>文档与课件</button></div>}
      {state.workspace && <nav className="lesson-workspace-navigation" aria-label="目录与课例">
        <section className="lesson-workspace-files" data-collapsed={!state.explorerOpen}><header><button type="button" className="lesson-section-heading" aria-expanded={state.explorerOpen} onClick={() => actions.setExplorerOpen(!state.explorerOpen)}><span>资源管理器</span><span aria-hidden="true">{state.explorerOpen ? '⌄' : '›'}</span></button><button type="button" className="lesson-icon-button" title="刷新工作空间根目录" aria-label="刷新工作空间根目录" onClick={actions.refreshTree}>↻</button></header>{state.explorerOpen && <><p className="lesson-section-note" title={state.workspace}>浏览工作空间中的真实文件</p><LessonDirectoryTree key={state.treeVersion} directory={state.workspace} operation={props.operation} onFile={entry => { void actions.openFile(entry) }} onDirectory={actions.setSelectedDirectory} /></>}</section>
        <section className="lesson-workspace-lessons" data-collapsed={!state.conversationsOpen}><header><button type="button" className="lesson-section-heading" aria-expanded={state.conversationsOpen} onClick={() => actions.setConversationsOpen(!state.conversationsOpen)}><span>课例与对话</span><span aria-hidden="true">{state.conversationsOpen ? '⌄' : '›'}</span></button><button type="button" className="lesson-icon-button" title="新建课例" aria-label="新建课例" onClick={() => actions.setCreating(true)}>＋</button></header>{state.conversationsOpen && <>{state.creating && <form className="lesson-create-form" onSubmit={event => { event.preventDefault(); void actions.run(actions.createLesson) }}><label>课例名称<input value={state.name} onChange={event => actions.setName(event.target.value)} required /></label><p title={state.selectedDirectory ? join(state.selectedDirectory, state.name.trim() || '课例名称') : undefined}>将创建：{state.selectedDirectory && join(state.selectedDirectory, state.name.trim() || '课例名称')}</p><button type="submit" className="lesson-primary-action" disabled={state.busy || !state.name.trim()}>创建课例</button><button type="button" onClick={() => actions.setCreating(false)}>取消</button></form>}<div className="lesson-lesson-actions"><button type="button" disabled={state.busy} onClick={() => { void actions.run(() => actions.openLesson()) }}>打开课例</button><details><summary>课例操作</summary><button type="button" disabled={state.busy} onClick={() => actions.setOpeningCopy(true)}>作为独立副本打开</button></details></div>{state.openingCopy && <div role="dialog" aria-modal="true" aria-label="作为独立课例副本打开"><p>请选择已复制的课例目录。副本会取得新的课例身份和对话，不继承原会话、候选或执行记录。</p><button type="button" disabled={state.busy} onClick={() => { actions.setOpeningCopy(false); void actions.run(() => actions.openLesson(true)) }}>选择副本目录并打开</button><button type="button" disabled={state.busy} onClick={() => actions.setOpeningCopy(false)}>取消</button></div>}<ul className="lesson-list">{state.lessons.map(item => <li key={item.identity.lessonId + item.identity.normalizedDirectory}><button type="button" title={item.identity.normalizedDirectory} aria-pressed={item.identity.lessonId === state.lesson?.identity.lessonId} onClick={() => { void actions.run(() => actions.activate(item)) }}><strong>{item.manifest.title}</strong><small>{basename(item.identity.normalizedDirectory)}</small></button></li>)}</ul>{state.lesson && <LessonConversationNavigation lesson={state.lesson} conversations={state.conversations} currentId={state.conversation?.conversationId} operation={props.operation} onRecordsChange={actions.setConversations} onDeleted={ids => { if (state.conversation && ids.includes(state.conversation.conversationId)) actions.clearConversation() }} onSelect={item => actions.selectConversation(item)} />}</>}</section>
      </nav>}
      {state.workspace && <main className="lesson-workspace-chat" aria-label="课例对话">{state.lesson && state.conversation ? <><details className="lesson-workflow" open={state.workflowOpen} onToggle={event => actions.setWorkflowOpen((event.currentTarget as HTMLDetailsElement).open)}><summary><span>创作流程</span><small>查看当前阶段、确认稿件或处理待办</small></summary>{props.renderWorkflow?.(state.lesson, state.conversation)}</details>{props.renderChat(state.lesson, state.conversation, tabs.activeDocumentTarget())}</> : <section className="lesson-chat-empty"><p className="lesson-eyebrow">下一步</p><h2>选择或新建一个课例</h2><p>课例会获得独立目录、文档、材料和连续对话。</p><button type="button" className="lesson-primary-action" onClick={() => actions.setCreating(true)}>新建课例</button></section>}</main>}
      <section className="lesson-workspace-workbench" aria-label="课例工作台"><div role="tablist" aria-label="材料、教学文档与课件">{state.lesson && <button type="button" role="tab" aria-selected={tabs.activeTab === 'materials'} onClick={() => tabs.setActiveTab('materials')}>材料</button>}<button type="button" role="tab" aria-selected={tabs.activeTab === 'course'} onClick={() => tabs.setActiveTab('course')}>课件{props.projectPath && <small title={props.projectPath}>{basename(props.projectPath)}</small>}</button>{tabs.tabs.map(tab => <TabButton key={tab.path} tab={tab} active={tabs.activeTab === tab.path} onSelect={() => tabs.setActiveTab(tab.path)} onClose={() => { void actions.run(async () => { if (!(await tabs.closeTab(tab))) throw new Error('当前稿尚未保存，请重试保存、保留恢复稿或返回编辑。') }) }} />)}</div>{state.lesson && <div className="lesson-file-tab" hidden={tabs.activeTab !== 'materials'}>{props.renderMaterials?.(state.lesson) ?? <section className="lesson-workbench-empty"><p className="lesson-eyebrow">材料</p><h2>添加本课例需要的材料</h2><p>材料会整理到当前课例，供后续教学策划和生成使用。</p></section>}</div>}<div className="lesson-course-tab" hidden={tabs.activeTab !== 'course'}>{props.children}</div>{tabs.tabs.map(tab => <div key={tab.path} hidden={tabs.activeTab !== tab.path} className="lesson-file-tab">{tab.kind === 'document' && tab.lesson ? <LessonDocumentEditor ref={editor => tabs.registerEditor(tab.path, editor)} documentRef={{ lessonId: tab.lesson.identity.lessonId, lessonDirectory: tab.lesson.identity.normalizedDirectory, relativePath: relativeFile(tab.lesson, tab.path)! }} port={props.documentPort} onClosed={() => tabs.removeTab(tab.path)} onDirtyChange={dirty => tabs.updateDirty(tab.path, dirty)} /> : props.renderMaterial?.(tab.path, tab.lesson) ?? <p>此文件的预览暂不可用：{tab.path}</p>}</div>)}</section>
    </div>
  </div>
}

function TabButton({ tab, active, onSelect, onClose }: { tab: LessonFileTab; active: boolean; onSelect(): void; onClose(): void }) {
  return <span className="lesson-workbench-tab"><button type="button" role="tab" title={tab.path} aria-selected={active} onClick={onSelect}><span>{tab.name}</span>{tab.dirty && <i aria-label="未保存" title="未保存" />}</button><button type="button" className="lesson-icon-button" aria-label={`关闭 ${tab.name}`} onClick={onClose}>×</button></span>
}
